# Site settings
title: 越努力越幸运
SEOTitle: 张海超的个人博客
header-img: img/post-bg-coffee.jpeg
email: zhanghaichao961@gmail.com
description: "java工程师，热爱技术。很高兴能在这里与你分享我对技术和生活的思考。"
keyword: "张海超, 张海超的个人博客, 张海超的博客, 后端, 后端开发, 后端博客, java, python, android"
url: "http://zhanghaichao520.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/zhanghaichao520/zhanghaichao520.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "我们一起玩，顺便赚点钱，然后活到一百岁"
sidebar-avatar: /img/avatar_m.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     u/3534383631?refer_flag=1001030101_&is_all=1
zhihu_username:     xiao-chao-99-1
github_username:    zhanghaichao520
facebook_username:  profile.php?id=100010723339047
#jianshu_username:   e71990ada2fd





# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 66d262e177464fc80cbd                            #生成的clientID
  clientSecret: f88031b7e98d94348eef3f5f186169068a35cbef    #生成的clientSecret
  repo: zhanghaichao520.github.io    #仓库名称
  owner: zhanghaichao520    #github用户名
  admin: zhanghaichao520
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto            # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto



# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "周老师",
        href: "https://github.com/zhouzhou-96"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
